#!/usr/bin/python3

import datetime
import psycopg2
import sqlalchemy 

from sqlalchemy import create_engine
from sqlalchemy import text 

TIME = datetime.datetime.now()


def get_engine():

    # dialect[+driver]://user:password@host/dbname[?key=value..]
    engine = create_engine("postgresql+psycopg2://admin:p0stdev@0.0.0.0", echo=True)
    return engine


def execute():

    db = get_engine()
    with db.connect() as conn:
        conn.execute(
            text("SELECT * FROM benchpress")
        )
        conn.execute"(text("CREATE TABLE benchpress (date int,sets int, reps int, weight int)"))
        conn.execute(
            text("INSERT INTO benchpress (date, sets, reps, weight) VALUES (:date, :sets, :reps, :weight)"),
            [{  
                "date": TIME.strftime("%Y%M%d"),
                "sets": 3, 
                "reps": 10, 
                "weight": 145
            }]
        )
        conn.commit()

if __name__ == '__main__':
    execute()
#breakpoint()
