#!/usr/bin/python3

import psycopg2

from sqlalchemy import create_engine


# dialect[+driver]://user:password@host/dbname[?key=value..]
engine = create_engine("postgresql+psycopg2://admin:p0stdev@127.0.0.1:9876/postgre-sql", echo=True)

breakpoint()
