#!/usr/bin/python3
import datetime
import random
import click
from typing import List
from typing import Optional
from sqlalchemy import create_engine, Column, Integer, String, select
from sqlalchemy.orm import Mapped, mapped_column, relationship, DeclarativeBase, Session


# Create the base class as a subclass of DB class
class Base(DeclarativeBase):
    pass

class Strength(Base):
    
    __tablename__ = "strength_training"

    id: Mapped[int] = mapped_column(primary_key=True)
    date: Mapped[int] 
    exercise: Mapped[str] = mapped_column(String(30))
    sets: Mapped[int]
    reps: Mapped[int]
    weight: Mapped[Optional[int]]
   
    def __repr__(self) -> str:
        return f"Strength(id={self.id!r},date={self.date!r},exercise={self.exercise!r},sets={self.sets!r},reps={self.reps!r},weight={self.weight!r})"

class Endurance(Base):
    
    __tablename__ = "endurance_training"

    id: Mapped[int] = mapped_column(primary_key=True)
    date: Mapped[int]
    exercise: Mapped[str] = mapped_column(String(30))
    time: Mapped[int]
    distance: Mapped[int]
   
    def __repr__(self) -> str:
        return f"Endurance(id={self.id!r},date={self.date!r},exercise={self.exercise!r},time={self.time!r},distance={self.distance!r})"

# Exercise input validation
def exercise_validation(table_name):
    
    if table_name == 'Strength':
        exercise_list=['benchpress','barbell_squat','barbell_curl']
    else:
        exercise_list=['road_run','trail_run','road_bike','mountain_bike','swim']
    while True:
        a = input("Enter Exercise name: ")
        if a in exercise_list:
            return a
        print(f"'{a}' not a valid exercise for this database")
        print("Valid exercise names:\n")
        for i in exercise_list:
            print(i)

# Integer input validation  
def int_validation(msg):
   
    while True:
        print(msg)
        a = input() 
        try:
            int(a)
            return a
        except Exception as e:
            print(f"expected datatype int got '{type(a)}'")

# Float input Validation
def flt_validation(msg):

    while True:
        print(msg)
        a = input()
        try:
            float(a)
            return a
        except Exception as e:
            print(f"expected datatype float got '{type(a)}'") 

def pick_table():
    table = input("Table to Retrieve [ Strength | Endurance ]: ").title()   
    return table

def insert(*args,**kwargs):

    table_name = pick_table()
    if table_name == 'Strength':

        with Session(engine) as session:
            entry = Strength(
                exercise=exercise_validation(table_name),
                date=TIME.strftime("%Y%M%d"),
                sets=int_validation(msg="Enter # of Sets: "),
                reps=int_validation(msg="Enter # of Reps: "),
                weight=int_validation(msg="Enter # of Weight: ")
            )
            session.add_all([entry])
            session.commit()

    elif table_name == 'Endurance':

        with Session(engine) as session:
            entry = Endurance(
                exercise=exercise_validation(table_name),
                date=TIME.strftime("%Y%M%d"),
                time=int_validation(msg="Enter total minutes: "),
                distance=flt_validation(msg="Enter total miles: ")
            )
            session.add_all([entry])
            session.commit()
    else:
        print(f"Expected 'Strength' or 'Endurance' got '{pick_table}'")
        insert(*args,**kwargs)

# TODO def pick_table()
def retrieve():
    
    while True:
        pick_table()
        
        if pick_table == 'Strength':
            with Session(engine) as session:
                result = session.execute(select(Strength).order_by(Strength.id))
                for i in result.all():
                    print(i[0])
            return

        elif pick_table == 'Endurance':
            with Session(engine) as session:
                result = session.execute(select(Endurance).order_by(Endurance.id))
                for i in result.all():
                    print(i[0])
            return

        else:
            print(f"Expected 'Strength' or 'Endurance' got '{pick_table}'")
            retrieve()

def delete():
    pass

def main():
    action = 'insert'
    if action == 'insert':
        cont='y'
        while cont == 'y':
            insert()
            cont = input("Do you have more entries? (y/n): ")
    if action == 'retrieve':
        retrieve()
    
if __name__ == '__main__':
    TIME = datetime.datetime.now()
    # Create an engine to connect to the database
    engine = create_engine("postgresql+psycopg2://admin:p0stdev@0.0.0.0")
    # Create the Tables with the metadata and engine
    Base.metadata.create_all(engine)
    
    main()
