# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.4
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options:/home/mcstarky/workout_schedule/data/volume: Z
  creationTimestamp: "2023-04-18T10:57:39Z"
  labels:
    app: postgre-sql
  name: postgre-sql
spec:
  containers:
  - image: docker.io/dpage/pgadmin4:latest
    name: webdb
    ports:
    - containerPort: 5432
      hostPort: 5432
    - containerPort: 80
      hostPort: 8080
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/pgadmin
      name: 4cba2f9ed492fa8ce54e2a55ff08991d831a390e6eb7f770331c5dc14075c4b3-pvc
  - args:
    - postgres
    image: docker.io/library/postgres:14
    name: db
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: home-mcstarky-workout_schedule-data-volume-host-0
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /home/mcstarky/workout_schedule/data/volume
      type: Directory
    name: home-mcstarky-workout_schedule-data-volume-host-0
  - name: 4cba2f9ed492fa8ce54e2a55ff08991d831a390e6eb7f770331c5dc14075c4b3-pvc
    persistentVolumeClaim:
      claimName: 4cba2f9ed492fa8ce54e2a55ff08991d831a390e6eb7f770331c5dc14075c4b3
status: {}

